### ISSUE TITLE
1.8-1.12 version support

### ISSUE THREAD

**Issue by denmeh** [unldenis/Corpse#1]
As you may have noticed versions 1.8 -1.12 are not supported, why?
Because from [1.13 it is possible](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/EnumWrappers.java#L375) to set the pose of the npc to SLEEPING.
In previous versions instead you have to use a PacketPlayOutBed, which causes problems.

Using this code I can make him sleep, however I cannot make the bed invisible.
```java
Location location=...
player.sendBlockChange(location, Material.valueOf("BED_BLOCK"), (byte) 0);
player.sendBlockChange(location.add(0, 0, 1), Material.valueOf("BED_BLOCK"), (byte) 2);

PacketContainer packet = new PacketContainer(PacketType.Play.Server.BED);
BlockPosition blockPos = new BlockPosition(location.getBlock().getX(), location.getBlock().getY(), location.getBlock().getZ());
packet.getIntegers().write(0, id);
packet.getBlockPositionModifier().write(0, blockPos);
```
[Preview Result](https://user-images.githubusercontent.com/80055679/150601268-c95d5fb2-3711-4055-ae16-8ffd503b3a24.png)

As you can see in the image the npc skin is not visible, why? because in this version(1.8.8) a [ClassNotFoundException](https://github.com/unldenis/Corpse/blob/c89b9a8c7df9e6c960887c154756960380084bb6/src/main/java/com/github/unldenis/corpse/logic/Corpse.java#L75) is thrown referring to the Guava MultiMap.
The solution is * not * to import the entire library as it weighs 3MB.

**Comment by Happy-FZM** [comment]
I tested this code and it works (1.12.2).
I found that it only works when use ProtocolLibrary.getProtocolManager().sendServerPacket().
If you use ProtocolLibrary.getProtocolManager().broadcastServerPacket() it not works.

      public static PacketContainer PLAYER_SLEEPING(Location loc, int entityId) {
          PacketContainer packet = ProtocolLibrary.getProtocolManager().createPacket(PacketType.Play.Server.BED);
          packet.getIntegers().write(0, entityId);
          packet.getBlockPositionModifier().write(0, new BlockPosition(loc.getBlockX(), loc.getBlockY(), loc.getBlockZ()));
          return packet;
      }
